version: "3"
services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soft_bank
    networks:
      - soft-bank
    ports:
      - 55436:5432
    volumes:
      - soft-bank-db-data:/var/lib/postgresql/data
networks:
  soft-bank:
volumes:
  soft-bank-db-data:
